#
# _config.yml for andrew.marcuse.info
#

exclude: [ "CNAME", "README.md", "LICENSE.txt", "tmp", "*.sh", "**/*_src*" ]
permalink: /blog/:year/:month/:day/:title/index.html
production_url: https://emoji.fileformat.info
title: FileFormat.Info Emoji SVGs 
markdown: kramdown
plugins:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

google_analytics_id: UA-328425-43
google_validation: LATER
bing_validation: LATER
